# Graphics
INFORMATION_FIELD_HEIGHT = 0.1  # As part of the screen height
EVOLUTION_FIELD_OUTLINE_WIDTH = 1
SURFACE_CORNER = (EVOLUTION_FIELD_OUTLINE_WIDTH, EVOLUTION_FIELD_OUTLINE_WIDTH)
FPS = 100
FONT_SIZE = 15
PAUSE = 0.3  # In seconds

# Body
BODY_RADIUS = 5
REACH_LENGTH = BODY_RADIUS + BODY_RADIUS  # How far a body can reach
BODY_SPEED = 1
ENERGY_FOR_MOVING = 1  # For one move
CHANGE_INSTINCT_ANGLE_PROBABILITY = 0.002
ARROW_LENGTH = 28

ARROW_WIDTH = 2
ARROWHEAD_LENGTH = 0.2 * ARROW_LENGTH
ARROW_ANGLE = 60

from math import radians, sqrt

ANGLE_RAD_HALF = radians(ARROW_ANGLE) / 2
N_DIRECTIONS = 23  # The number has to be prime!

# Plants
PLANT_SIDE = BODY_RADIUS * sqrt(2)
